on:
  schedule: 
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      bool_one:
        type: boolean
        default: true
      bool_two:
        type: boolean
        default: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ inputs.bool_one }} and ${{ inputs.bool_two }}'
